export const privacyPolicies = {
  "maxxed-remote": {
    effectiveDate: "June 23, 2026",
    overview: "Maxxed Remote controls compatible televisions over the user's local network. Version 1 does not create accounts, collect analytics, transmit personal data to Maxxed Technical Systems, or include an active advertising SDK.",
    dataProcessed: [
      "Television names or user-assigned nicknames",
      "Local television IP addresses and device identifiers",
      "Pairing credentials and certificate fingerprints",
      "Local network state needed to discover and control a television",
    ],
    permissions: [
      ["Internet", "Communicate with compatible televisions over the local network."],
      ["Network and Wi-Fi state", "Confirm network availability and support local discovery."],
      ["Wi-Fi multicast", "Receive SSDP discovery responses from compatible televisions."],
      ["Nearby Wi-Fi devices", "Support local Wi-Fi discovery on Android versions that require this permission."],
    ],
    storage: "Saved televisions, pairing credentials, and trust fingerprints remain in app-private storage. Pairing secrets are protected with Android Keystore encryption.",
    sharing: "Version 1 does not send saved television information or pairing credentials to Maxxed Technical Systems or advertising, analytics, or data-broker services.",
    retention: "Saved television records remain until the user removes a television, clears app data, or uninstalls the app.",
    deletion: "Delete individual saved televisions inside the app. Clearing Android app storage or uninstalling removes the remaining local data.",
    thirdParties: "Television manufacturers receive commands over the user's local network according to the television's own software and privacy practices. Maxxed Remote does not proxy those commands through a developer server.",
    children: "Maxxed Remote is a general utility and is not designed to collect personal information from children.",
  },
  "maxxed-compass": {
    effectiveDate: "June 23, 2026",
    overview: "Maxxed Compass processes device sensors, location, trip history, and an optional live camera preview on the device. The app requests no internet permission and contains no advertising, analytics, account, or cloud-sync SDK.",
    dataProcessed: [
      "Compass, accelerometer, magnetometer, and orientation readings",
      "Precise or approximate location for declination, trips, coordinates, and sky calculations",
      "Trip points, segments, distance, duration, and locally assigned trip names",
      "Live camera frames used only for the optional Sky Scanner preview",
      "Settings, units, display preferences, and calibration state",
    ],
    permissions: [
      ["Precise or approximate location", "Calculate true north, coordinates, sky positions, and trip distance."],
      ["Background location", "Continue or restore a trip the user explicitly started while the app is not visible."],
      ["Camera", "Show an optional live Sky Scanner preview. The app does not capture or retain camera frames."],
      ["Notifications", "Display trip status with Pause, Resume, and Stop actions."],
      ["Foreground location service", "Continue an active trip with a visible Android notification."],
      ["Start after reboot", "Restore a previously active, unpaused trip after device restart."],
    ],
    storage: "Settings, active trip state, trip points, segments, and history are stored in Android app-private storage. Camera frames are processed ephemerally and are not saved.",
    sharing: "The app does not transmit sensor, location, trip, or camera data off the device and does not share it with third parties.",
    retention: "Trip data remains until the user deletes a trip, deletes all local history, clears app data, or uninstalls the app.",
    deletion: "Delete individual trips or all trip history from the app's advanced tools. Android clear-storage and uninstall also remove app-private data, subject to Android backup settings.",
    thirdParties: "No third-party advertising, analytics, account, or cloud-sync service is active in the current app.",
    children: "The app is a navigation utility and is not directed to children. Location features require device permission controlled by the device owner.",
  },
  "maxxed-measure": {
    effectiveDate: "June 23, 2026",
    overview: "Maxxed Measure uses the camera and user-entered reference dimensions to create camera-assisted measurement estimates. Measurement images and history are intended to stay on the device unless the user explicitly exports them.",
    dataProcessed: [
      "Live camera frames and user-captured measurement images",
      "Known-reference dimensions and selected measurement units",
      "User-adjusted calibration and measurement endpoints",
      "Measurement results, uncertainty, notes, names, and annotated captures",
      "Export destinations selected through Android's system interface",
    ],
    permissions: [
      ["Camera", "Preview and capture the subject and known-size reference used for a measurement."],
      ["Document access", "Let the user explicitly choose a destination when exporting a result."],
    ],
    storage: "Captures, annotations, calibration data, and saved measurement history are stored in app-private storage unless the user chooses an export destination.",
    sharing: "The app does not automatically upload measurements. Data leaves app-private storage only when the user copies, shares, or exports it.",
    retention: "Saved measurements remain until deleted by the user, app storage is cleared, or the app is uninstalled.",
    deletion: "Delete individual history items in the app. Clear Android app storage or uninstall to remove remaining app-private records.",
    thirdParties: "Android's document picker or share interface may pass an exported copy to a destination selected by the user. That destination's privacy practices then apply.",
    children: "Maxxed Measure is a general utility and is not designed to collect personal information from children.",
  },
  "maxxed-gold-estimator": {
    effectiveDate: "June 23, 2026",
    overview: "Maxxed Gold Estimator performs guided image capture and conservative visual material estimation on the device. It has no account, advertising SDK, analytics SDK, cloud sync, or network permission.",
    dataProcessed: [
      "Six guided sample photographs",
      "Device orientation used to confirm view coverage",
      "Known-reference dimensions and optional measured total batch weight",
      "Subject masks, visible color clusters, user material assignments, and confidence ranges",
      "Saved batch names, comparisons, notes, and user-directed CSV exports",
    ],
    permissions: [
      ["Camera", "Capture the six sample views used for on-device visual analysis."],
      ["Device motion sensors", "Confirm adequate separation between requested capture angles."],
      ["Document access", "Let the user explicitly select a destination for CSV export."],
    ],
    storage: "Captures and saved batches remain in app-private storage and are excluded from backup where supported by the final Android configuration.",
    sharing: "The app does not transmit sample photographs, estimates, or batch data. A CSV leaves app-private storage only after the user chooses a destination.",
    retention: "Captures and batch results remain until the user deletes the batch, clears app data, or uninstalls the app.",
    deletion: "Delete saved batches inside the app. Android clear-storage and uninstall remove remaining app-private data.",
    thirdParties: "A user-selected document or sharing destination controls any exported copy. The current app does not use a remote analysis provider.",
    children: "The app is a field estimation tool and is not directed to children.",
  },
  "fishing-maxxed": {
    effectiveDate: "June 23, 2026",
    overview: "Fishing Maxxed is an offline-first catch journal. It stores catch records locally, keeps exact coordinates private by default, and redacts exact coordinates from standard exports.",
    dataProcessed: [
      "Catch photographs and known-reference measurement points",
      "User-confirmed species, length, optional weight, method, notes, and catch status",
      "Exact location stored privately and a broader region used for privacy-safe records",
      "Catch dates, local history, filters, and on-device leaderboard results",
      "User-directed CSV or sharing exports",
    ],
    permissions: [
      ["Camera", "Capture a catch photograph and known reference for measurement."],
      ["Location", "Attach an exact private location and derive a broader region when the user allows it."],
      ["Document or sharing access", "Let the user explicitly export a privacy-safe record."],
    ],
    storage: "Catch photos, exact coordinates, measurements, species confirmation, and notes are stored in app-private local storage.",
    sharing: "The app does not provide cloud sync or a global leaderboard. Standard exports redact exact coordinates. A user may still choose to share other record content through Android.",
    retention: "Catch records remain until the user edits or deletes them, clears app storage, or uninstalls the app.",
    deletion: "Delete individual catches from the local journal. Clear Android app storage or uninstall to remove all remaining app-private records.",
    thirdParties: "A destination selected through Android's share or document interface controls the exported copy. Bundled regulation fixtures are non-authoritative and do not transmit catch data.",
    children: "Fishing Maxxed is an outdoor recordkeeping tool and is not directed to children. Device owners control camera and location permission.",
  },
  "rival-rush": {
    effectiveDate: "June 23, 2026",
    overview: "Rival Rush is a local party game. The audited internal-test source uses local player profiles, local gameplay metrics, a no-operation production analytics provider, an unavailable Google Play Games sign-in stub, and a no-operation advertising provider unless an advertising build flag and provider are deliberately enabled.",
    dataProcessed: [
      "Player display names, avatar selections, settings, and local profile identifiers",
      "Local wins, losses, scores, coins, experience, unlocks, challenges, and game progress",
      "Local gameplay counters such as game mode opened, match started, and match completed",
      "Diagnostic logs in development builds",
      "Advertising ID only if a future ad-enabled production build activates an advertising SDK",
    ],
    permissions: [
      ["Internet", "Reserved for Google Play delivery and any production service explicitly enabled in a future build."],
      ["Advertising ID", "Used only if an ad-enabled build activates a disclosed advertising provider. The current no-operation provider does not request an ad."],
      ["Notifications", "May be used for game reminders only if the user grants permission and the feature is enabled."],
    ],
    storage: "Player identity, profile, progress, settings, rewards, and gameplay metrics are stored locally through the game's save system. The current Google Play Games provider is a non-functional stub and does not create a remote account.",
    sharing: "The current production analytics path is no-operation and does not send gameplay events to Maxxed Technical Systems. The current advertising path is also no-operation unless an ad SDK is deliberately enabled for a later build.",
    retention: "Local profile and gameplay data remain until reset in the app where available, Android app storage is cleared, or the game is uninstalled.",
    deletion: "Clear local profile or progress controls where offered, or use Android clear-storage or uninstall to remove all app-private game data.",
    thirdParties: "Google Play processes installation, account, purchase, and platform diagnostics under Google's terms. If Unity Ads, another ad provider, Google Play Games, Firebase, or remote analytics is enabled later, this policy and the Play Data safety declaration must be updated before that build is released.",
    children: "Rival Rush is intended for a general audience. The final age targeting, advertising configuration, and store declarations must be reviewed together before public release.",
  },
};
