export const privacyPolicies = {
  "maxxed-remote": {
    effectiveDate: "June 25, 2026",
    overview: "Maxxed Remote controls compatible televisions over the user's local network. The current documented release does not create a Maxxed account, collect analytics, transmit personal data to Maxxed Technical Systems, sell personal data, or include an active advertising SDK. The app is designed so saved television details and pairing credentials stay on the user's device unless the user separately sends support information by email.",
    dataProcessed: [
      "Television names, manufacturer labels, model labels where available, or user-assigned nicknames",
      "Local television IP addresses, local-network discovery responses, and device identifiers needed to reconnect",
      "Pairing credentials, authorization tokens, secure-session material, and certificate fingerprints used to control a paired television",
      "Local network state, Wi-Fi state, and connectivity information needed to discover and control compatible televisions",
      "User settings such as preferred TV, saved shortcuts, keypad state, and connection preferences",
      "Support details only if the user chooses to email them, such as device model, app version, TV model, and troubleshooting notes",
    ],
    permissions: [
      ["Internet", "Communicate with compatible televisions and supported TV control interfaces over the user's local or private network."],
      ["Network and Wi-Fi state", "Confirm network availability, detect connection changes, and support local discovery."],
      ["Wi-Fi multicast", "Receive SSDP or similar local discovery responses from compatible televisions."],
      ["Nearby Wi-Fi devices", "Support local Wi-Fi discovery on Android versions that require this permission for nearby network devices."],
    ],
    storage: "Saved televisions, pairing credentials, trust fingerprints, shortcuts, and connection preferences remain in Android app-private storage. Pairing secrets are protected with Android Keystore-backed encryption where supported. The app does not maintain a developer-operated cloud copy of saved televisions.",
    sharing: "The app does not send saved television information, pairing credentials, local IP addresses, or viewing behavior to Maxxed Technical Systems, advertising networks, analytics providers, or data brokers. Information leaves the app only when the user deliberately sends support details, uses Android sharing, or communicates directly with the television on the local network.",
    retention: "Saved television records and settings remain until the user removes a television, clears app data, or uninstalls the app. Support emails are retained only as long as reasonably needed for support, abuse prevention, operational records, or legal obligations.",
    deletion: "Delete individual saved televisions inside the app. Clearing Android app storage or uninstalling removes the remaining local data. To request deletion of support emails or beta/support records sent to Maxxed Technical Systems, email privacy@techmaxxed.com from the address used for the request.",
    thirdParties: "Television manufacturers receive commands over the user's local network according to the television's own software, pairing flow, firmware, and privacy practices. Google Play may process installation, purchase, crash, security, and device diagnostics under Google's policies. Maxxed Remote does not proxy TV commands through a developer server.",
    children: "Maxxed Remote is a general utility and is not directed to children. It is not designed to knowingly collect personal information from children.",
  },
  "maxxed-compass": {
    effectiveDate: "June 25, 2026",
    overview: "Maxxed Compass processes device sensors, location, trip history, and optional live camera preview data on the device. The current documented app requests no internet permission and contains no advertising, analytics, account, or cloud-sync SDK. It is designed so navigation and trip data remain local unless the user deliberately exports or emails information.",
    dataProcessed: [
      "Compass, accelerometer, gyroscope, magnetometer, rotation-vector, calibration, and orientation readings",
      "Precise or approximate location for declination, trips, coordinates, distance, and sky-position calculations",
      "Trip points, route segments, distance, duration, timestamps, pause/resume state, and locally assigned trip names",
      "Live camera frames used only for the optional Sky Scanner preview and not retained as captures by the documented app",
      "Settings, units, night-mode preferences, display preferences, calibration state, and active-trip recovery state",
      "Support details only if the user chooses to email them, such as device model, Android version, app version, screenshots, or troubleshooting notes",
    ],
    permissions: [
      ["Precise or approximate location", "Calculate true north, coordinates, sky positions, trip distance, and trip history when the user enables those features."],
      ["Background location", "Continue or restore a trip the user explicitly started while the app is not visible, with Android-controlled permission and notification behavior."],
      ["Camera", "Show an optional live Sky Scanner preview. The documented app does not capture, upload, or retain camera frames for this feature."],
      ["Notifications", "Display trip status with Pause, Resume, Stop, and recovery actions where supported by Android."],
      ["Foreground location service", "Continue an active trip with a visible Android notification."],
      ["Start after reboot", "Restore a previously active, unpaused trip after device restart when Android allows it."],
    ],
    storage: "Settings, active trip state, trip points, route segments, and history are stored in Android app-private storage. Camera preview frames are processed ephemerally and are not saved by the documented Sky Scanner flow. Local data is not uploaded to a Maxxed cloud service.",
    sharing: "The app does not transmit sensor, location, trip, or camera-preview data off the device and does not share it with advertising, analytics, or data-broker services. Data leaves the device only if the user separately exports, screenshots, or emails it outside the app.",
    retention: "Trip data and settings remain until the user deletes a trip, deletes all local history, clears app data, or uninstalls the app. If the user sends support email, that email is retained only as long as reasonably needed for support, abuse prevention, operational records, or legal obligations.",
    deletion: "Delete individual trips or all trip history from the app's advanced tools. Android clear-storage and uninstall also remove app-private data, subject to Android backup settings controlled by the device and operating system. Email privacy@techmaxxed.com to request deletion of support records sent to Maxxed Technical Systems.",
    thirdParties: "No third-party advertising, analytics, account, or cloud-sync service is active in the current documented app. Google Play may process installation, security, crash, and device diagnostics under Google's policies.",
    children: "The app is a navigation utility and is not directed to children. Location, camera, and notification features require device permissions controlled by the device owner.",
  },
  "maxxed-measure": {
    effectiveDate: "June 25, 2026",
    overview: "Maxxed Measure uses the camera and user-entered reference dimensions to create camera-assisted measurement estimates. Measurement images, annotations, calibration data, and history are intended to stay on the device unless the user explicitly exports, shares, screenshots, or emails them.",
    dataProcessed: [
      "Live camera frames and user-captured measurement images",
      "Known-reference dimensions, calibration ratios, chosen measurement units, and user-selected precision display",
      "User-adjusted calibration points, measurement endpoints, ruler overlays, confidence or uncertainty values, and annotations",
      "Measurement results, names, notes, timestamps, saved history records, and annotated captures",
      "Export destinations selected through Android's system document picker or share interface",
      "Support details only if the user chooses to email them, such as app version, device model, screenshots, measurement examples, or troubleshooting notes",
    ],
    permissions: [
      ["Camera", "Preview and capture the subject and known-size reference used for a measurement."],
      ["Document access", "Let the user explicitly choose a destination when exporting a result."],
      ["Media or photo access where required by Android", "Read or write only the user-selected image or export destination when Android requires a scoped permission or picker flow."],
    ],
    storage: "Captures, annotations, calibration data, settings, and saved measurement history are stored in Android app-private storage unless the user chooses an export destination. The app is designed for local processing and does not maintain a developer-operated cloud copy of measurement records.",
    sharing: "The app does not automatically upload measurements, images, calibration records, or history. Data leaves app-private storage only when the user copies, shares, exports, screenshots, or emails it. User-selected export destinations and receiving apps control their own copies.",
    retention: "Saved measurements remain until deleted by the user, app storage is cleared, or the app is uninstalled. Exported copies remain wherever the user saved or shared them. Support emails are retained only as long as reasonably needed for support, abuse prevention, operational records, or legal obligations.",
    deletion: "Delete individual history items in the app. Clear Android app storage or uninstall to remove remaining app-private records. Delete exported copies from the destination chosen by the user. Email privacy@techmaxxed.com to request deletion of support records sent to Maxxed Technical Systems.",
    thirdParties: "Android's document picker, photo picker, or share interface may pass an exported copy to a destination selected by the user. That destination's privacy practices then apply. Google Play may process installation, security, crash, and device diagnostics under Google's policies.",
    children: "Maxxed Measure is a general utility and is not directed to children. It is not designed to knowingly collect personal information from children.",
  },
  "maxxed-gold-estimator": {
    effectiveDate: "June 25, 2026",
    overview: "Maxxed Gold Estimator performs guided image capture and conservative visual material estimation on the device. The current documented app has no account, advertising SDK, analytics SDK, cloud sync, or network permission. It provides visual estimates only and does not perform assay, valuation, or chemical verification.",
    dataProcessed: [
      "Guided sample photographs, including multiple viewing angles and quality checks",
      "Device orientation or motion data used to confirm view coverage and separation between requested angles",
      "Known-reference dimensions, optional measured total batch weight, and user-entered context",
      "Subject masks, visible color clusters, user material assignments, confidence ranges, and conservative estimate outputs",
      "Saved batch names, comparisons, notes, timestamps, and user-directed CSV exports",
      "Support details only if the user chooses to email them, such as app version, device model, screenshots, fixture examples, or troubleshooting notes",
    ],
    permissions: [
      ["Camera", "Capture the sample views used for on-device visual analysis."],
      ["Device motion sensors", "Confirm adequate separation between requested capture angles and improve guided capture quality."],
      ["Document access", "Let the user explicitly select a destination for CSV export."],
      ["Media or photo access where required by Android", "Read or write only the user-selected image or export destination when Android requires a scoped permission or picker flow."],
    ],
    storage: "Captures, masks, user corrections, saved batches, notes, and estimates remain in Android app-private storage and are excluded from backup where supported by the final Android configuration. The app is designed for local processing and does not maintain a developer-operated cloud copy of sample photographs or estimates.",
    sharing: "The app does not transmit sample photographs, material assignments, estimates, or batch data to Maxxed Technical Systems, advertising networks, analytics providers, assay providers, or data brokers. A CSV, screenshot, or shared summary leaves app-private storage only after the user chooses a destination.",
    retention: "Captures and batch results remain until the user deletes the batch, clears app data, or uninstalls the app. Exported copies remain wherever the user saved or shared them. Support emails are retained only as long as reasonably needed for support, abuse prevention, operational records, or legal obligations.",
    deletion: "Delete saved batches inside the app. Android clear-storage and uninstall remove remaining app-private data. Delete exported copies from the destination chosen by the user. Email privacy@techmaxxed.com to request deletion of support records sent to Maxxed Technical Systems.",
    thirdParties: "A user-selected document or sharing destination controls any exported copy. The current documented app does not use a remote analysis, assay, valuation, advertising, analytics, or cloud-sync provider. Google Play may process installation, security, crash, and device diagnostics under Google's policies.",
    children: "The app is a field estimation tool and is not directed to children. It is not designed to knowingly collect personal information from children.",
  },
  "fishing-maxxed": {
    effectiveDate: "June 25, 2026",
    overview: "Fishing Maxxed is an offline-first catch journal. It stores catch records locally, keeps exact coordinates private by default, redacts exact coordinates from standard exports, and does not operate a cloud leaderboard in the current documented release.",
    dataProcessed: [
      "Catch photographs, known-reference measurement points, calibration data, annotated captures, and uncertainty values",
      "User-confirmed species, length, optional weight, method, notes, catch status, and manual corrections",
      "Exact private location when permission is granted, plus broader region fields used for privacy-safer records and exports",
      "Catch dates, timestamps, local history, filters, local rankings, and on-device leaderboard results",
      "User-directed CSV, image, or sharing exports with exact-coordinate redaction in standard export flows",
      "Support details only if the user chooses to email them, such as app version, device model, screenshots, catch examples, or troubleshooting notes",
    ],
    permissions: [
      ["Camera", "Capture a catch photograph and known reference for measurement."],
      ["Location", "Attach an exact private location and derive a broader region when the user allows it."],
      ["Document or sharing access", "Let the user explicitly export a privacy-safer record or selected copy."],
      ["Media or photo access where required by Android", "Read or write only the user-selected image or export destination when Android requires a scoped permission or picker flow."],
    ],
    storage: "Catch photos, exact coordinates, measurements, species confirmation, notes, status, and local ranking data are stored in Android app-private local storage. The app is designed without developer-operated cloud sync or a global leaderboard for the current documented release.",
    sharing: "The app does not provide cloud sync or a global leaderboard in the documented release. Standard exports redact exact coordinates by default. A user may still choose to share other record content through Android, and the selected destination controls its own copy.",
    retention: "Catch records remain until the user edits or deletes them, clears app storage, or uninstalls the app. Exported copies remain wherever the user saved or shared them. Support emails are retained only as long as reasonably needed for support, abuse prevention, operational records, or legal obligations.",
    deletion: "Delete individual catches from the local journal. Clear Android app storage or uninstall to remove all remaining app-private records. Delete exported copies from the destination chosen by the user. Email privacy@techmaxxed.com to request deletion of support records sent to Maxxed Technical Systems.",
    thirdParties: "A destination selected through Android's share or document interface controls the exported copy. Bundled regulation fixtures are non-authoritative and do not transmit catch data. Google Play may process installation, security, crash, and device diagnostics under Google's policies.",
    children: "Fishing Maxxed is an outdoor recordkeeping tool and is not directed to children. Device owners control camera and location permissions.",
  },
  "rival-rush": {
    effectiveDate: "June 25, 2026",
    overview: "Rival Rush is a local party game. The audited internal-test source uses local player profiles, local gameplay metrics, a no-operation production analytics provider, an unavailable Google Play Games sign-in stub, and a no-operation advertising provider unless an advertising build flag and provider are deliberately enabled. Advertising, analytics, Google Play Games, and remote services must be reviewed and disclosed before any build enabling them is released.",
    dataProcessed: [
      "Player display names, avatar selections, settings, and local profile identifiers",
      "Local wins, losses, scores, coins, experience, unlocks, challenges, selected game modes, and progress",
      "Local gameplay counters such as game mode opened, match started, match completed, round results, and reset events",
      "Diagnostic logs in development or internal-test builds, which may include scene names, validation messages, device details, and error traces",
      "Advertising ID only if a future ad-enabled production build activates a disclosed advertising provider",
      "Support or beta details only if the user chooses to email them, such as tester account, app version, device model, screenshots, scene names, or bug notes",
    ],
    permissions: [
      ["Internet", "Reserved for Google Play delivery and any production service explicitly enabled in a future build."],
      ["Advertising ID", "Used only if an ad-enabled build activates a disclosed advertising provider. The current no-operation provider does not request an ad."],
      ["Notifications", "May be used for game reminders only if the user grants permission and the feature is enabled."],
    ],
    storage: "Player identity, profile, progress, settings, rewards, and gameplay metrics are stored locally through the game's save system. The current Google Play Games provider is a non-functional stub and does not create a remote game account in the documented internal-test build.",
    sharing: "The current production analytics path is no-operation and does not send gameplay events to Maxxed Technical Systems. The current advertising path is also no-operation unless an ad SDK is deliberately enabled for a later build. If a later build enables ads, analytics, cloud saves, leaderboards, purchases, or Google Play Games sign-in, the policy and Play Data safety declaration must be updated before release.",
    retention: "Local profile and gameplay data remain until reset in the app where available, Android app storage is cleared, or the game is uninstalled. Beta/support emails are retained only as long as reasonably needed for support, test administration, abuse prevention, operational records, or legal obligations.",
    deletion: "Clear local profile or progress controls where offered, or use Android clear-storage or uninstall to remove all app-private game data. Email privacy@techmaxxed.com to request deletion of beta/support records sent to Maxxed Technical Systems.",
    thirdParties: "Google Play processes installation, account, purchase, security, crash, and platform diagnostics under Google's terms. If Unity Ads, another ad provider, Google Play Games, Firebase, remote analytics, or cloud services are enabled later, this policy and the Play Data safety declaration must be updated before that build is released.",
    children: "Rival Rush is intended for a general audience. The final age targeting, advertising configuration, family-policy posture, and store declarations must be reviewed together before public release.",
  },
};