export const site = {
  name: "Maxxed Technical Systems",
  shortName: "Maxxed Technical",
  url: "https://techmaxxed.com",
  email: "support@techmaxxed.com",
  privacyEmail: "privacy@techmaxxed.com",
  betaEmail: "beta@techmaxxed.com",
  description: "Android apps, WordPress tools, and practical software for TV control, navigation, camera measurement, outdoor records, visual estimating, content maintenance, and local party games.",
};

export const apps = [
  {
    slug: "maxxed-remote",
    name: "Maxxed Remote",
    short: "Remote",
    category: "Utility",
    categoryKey: "utility",
    status: "Release prep",
    statusTone: "candidate",
    accent: "#25d0d8",
    icon: "TV",
    tagline: "One clean remote for the TVs you already own.",
    summary: "A focused Android TV remote for compatible Samsung Tizen and LG webOS televisions, with local-network control, saved TVs, keypad input, and app shortcuts.",
    description: "Control compatible televisions from one Android interface with discovery, pairing, saved devices, quick keypad input, app shortcuts, and local credential storage.",
    features: [
      ["Find compatible TVs", "Discover supported Samsung Tizen and LG webOS televisions on the same private network."],
      ["Pair with confidence", "TV approval and pairing credentials stay protected through Android app-private storage and Keystore support where available."],
      ["Use the controls that matter", "Navigate, adjust volume, change channels, enter keypad text, reopen saved TVs, and launch supported shortcuts."],
      ["Keep commands local", "Remote commands are designed for the private network instead of routing TV control through a Maxxed server."],
    ],
    facts: ["Android 8+", "Samsung Tizen", "LG webOS", "Local network"],
    privacy: "Pairing credentials are stored on the device. Remote-control traffic is designed to stay on the local network.",
    limitation: "Feature support varies by television model, firmware, region, and manufacturer control interface.",
    availability: "The signed Android build is in release preparation while television compatibility and store materials are verified.",
    featureImage: "maxxed-remote-feature.png",
    screenshots: [
      ["remote-control.png", "Maxxed Remote main control screen"],
      ["remote-discovery.png", "Maxxed Remote compatible TV discovery"],
      ["remote-saved-tvs.png", "Maxxed Remote saved televisions"],
      ["remote-keypad.png", "Maxxed Remote quick keypad"],
    ],
  },
  {
    slug: "maxxed-compass",
    name: "Maxxed Compass",
    short: "Compass",
    category: "Navigation",
    categoryKey: "outdoors",
    status: "Release prep",
    statusTone: "testing",
    accent: "#b9ed45",
    icon: "N",
    tagline: "Direction, distance, and sky tools without an account.",
    summary: "An offline Android compass with true-north guidance, trip tracking, recovery state, night display, local history, and calculated sky tools without an account requirement.",
    description: "Use live sensor headings, true north, trip tracking, recovery after interruption, night display, and calculated sky guidance without creating an account or relying on a Maxxed cloud service.",
    features: [
      ["Use real sensor signals", "Read rotation-vector headings with accelerometer and magnetometer fallback where supported."],
      ["Switch north modes", "Compare magnetic and true north with declination, calibration, and interference guidance."],
      ["Track trips locally", "Pause, resume, stop, segment, save, and recover active trip state on the device."],
      ["Check the sky", "Use calculated object positions, constellation dots, line patterns, red-map mode, and optional camera preview."],
    ],
    facts: ["Offline", "True north", "Trip history", "Metric and imperial"],
    privacy: "Sensor, location, trip, and optional camera-preview data are designed to stay on the device unless the user exports or emails it.",
    limitation: "Compass accuracy depends on the phone sensors, calibration, magnetic interference, and field conditions.",
    availability: "Core navigation and sky features are in release preparation while outdoor heading, notification, recovery, distance, sky comparison, and battery checks continue.",
  },
  {
    slug: "maxxed-measure",
    name: "Maxxed Measure",
    short: "Measure",
    category: "Measurement",
    categoryKey: "utility",
    status: "In development",
    statusTone: "development",
    accent: "#ff715b",
    icon: "↔",
    tagline: "Camera-assisted measuring with honest uncertainty.",
    summary: "A camera measurement app built around known-reference calibration, draggable endpoints, persistent ruler review, common units, confidence notes, saved history, and explicit export.",
    description: "Place a known-size reference in the same plane as the subject, calibrate the image, adjust measurement endpoints, and save or export an annotated estimate with visible uncertainty.",
    features: [
      ["Calibrate from a known reference", "Use a real object in the same image instead of pretending the camera can infer exact scale alone."],
      ["Correct both endpoints", "Drag measurement points, review the ruler overlay, and keep the evidence visible before saving."],
      ["Use practical units", "View inches, common fractions, feet, millimeters, centimeters, or meters."],
      ["Keep or export the result", "Save, rename, delete, copy, and explicitly export measurements and annotated captures."],
    ],
    facts: ["CameraX", "Known reference", "Multiple units", "Local history"],
    privacy: "Measurement captures and history are designed to remain local unless the user explicitly exports, shares, screenshots, or emails them.",
    limitation: "Camera-assisted measurements are estimates. The app will not claim survey, lab, or .001-inch accuracy.",
    availability: "Camera preview, calibration, correction, history, export, and known-object validation are moving through active development.",
  },
  {
    slug: "maxxed-gold-estimator",
    name: "Maxxed Gold Estimator",
    short: "Gold Estimator",
    category: "Field analysis",
    categoryKey: "outdoors",
    status: "Release prep",
    statusTone: "testing",
    accent: "#ffc44d",
    icon: "Au",
    tagline: "Conservative visual estimates, never assay claims.",
    summary: "An offline visual material estimator with guided multi-angle capture, reference scale, mask correction, material review, conservative ranges, saved batches, and CSV export.",
    description: "Capture guided views, calibrate against a known reference, review the subject mask and visible material assignments, then produce conservative ranges and confidence notes on the device.",
    features: [
      ["Capture multiple angles", "Collect top, side, rear, and oblique views with coverage and image-quality checks."],
      ["Review the analysis", "Adjust mask sensitivity and confirm or change visible-material groupings before trusting the output."],
      ["Read conservative ranges", "Review visible share, density assumptions, volume, weight, and confidence ranges with clear limitations."],
      ["Compare and export", "Save local batches, compare results, copy a summary, or choose a CSV destination."],
    ],
    facts: ["Offline analysis", "Multi-angle", "User correction", "CSV export"],
    privacy: "Captures remain in app-private storage and leave only when the user chooses an export or sharing destination.",
    limitation: "Color and surface appearance cannot identify chemistry. Results are not an assay, appraisal, or valuation.",
    availability: "The visual-estimate workflow is implemented and is moving through automated checks, signed build work, physical fixture testing, and final disclosures.",
  },
  {
    slug: "fishing-maxxed",
    name: "Fishing Maxxed",
    short: "Fishing",
    category: "Outdoors",
    categoryKey: "outdoors",
    status: "Release prep",
    statusTone: "testing",
    accent: "#47b7ff",
    icon: "FM",
    tagline: "A private catch journal built around evidence.",
    summary: "An offline-first fishing log with catch photos, known-reference length estimates, manual species confirmation, local records, private coordinates, and redacted exports.",
    description: "Photograph a catch, measure it against a real reference, adjust endpoints, confirm species yourself, and keep a local record without exposing exact coordinates by default.",
    features: [
      ["Measure against a reference", "Estimate length from a known object with draggable correction handles and visible uncertainty."],
      ["Confirm records yourself", "Species identification remains a user decision instead of an unsupported automated claim."],
      ["Keep coordinates private", "Store catch records locally and redact exact coordinates from standard exports."],
      ["Stay honest on rules", "Regulation fixtures can support checks, but users still verify current official fishing rules."],
    ],
    facts: ["Offline-first", "Catch history", "Location redaction", "Local rankings"],
    privacy: "Catch records stay private on the device, and standard exports redact exact coordinates by default.",
    limitation: "Users must check current official fishing regulations. The app cannot authorize a catch as legal to keep.",
    availability: "Functional source is present and moving through build, signing, known-object testing, device evidence, and regulation-source verification.",
  },
  {
    slug: "rival-rush",
    name: "Rival Rush",
    short: "Rival Rush",
    category: "Party game",
    categoryKey: "games",
    status: "Internal testing",
    statusTone: "candidate",
    accent: "#ff5fb7",
    icon: "RR",
    tagline: "Fast local competition for two.",
    summary: "A local Android party arcade with PickOff, RPS Arena, Tap Battle, and Word Rush, built for quick rounds, readable scores, player profiles, and couch competition.",
    description: "Jump between short competitive mini-games made for couples and friends on the same device, with quick resets, readable scores, player identity, and touch-first controls.",
    features: [
      ["PickOff", "Enter choices, run rapid eliminations, and keep a short winners history."],
      ["RPS Arena", "Play scored rock-paper-scissors rounds with ties, wins, and an optional one-round bot."],
      ["Tap Battle", "Race for taps against another player or an optional opponent mode."],
      ["Word Rush", "Use mobile A-Z controls to reveal words, track mistakes, and start a fresh round."],
    ],
    facts: ["Android first", "Local multiplayer", "Four mini-games", "Internal test"],
    privacy: "Player profiles and progress are designed for local play. Store disclosures will match the final advertising and analytics configuration.",
    limitation: "Features, art, and balance can change during internal testing.",
    availability: "The Android build is in Google Play internal testing while UX, credits, navigation, and Word Rush receive final polish.",
  },
];

const pluginAccents = ["#7dd3fc", "#86efac", "#facc15", "#fb7185", "#c084fc", "#25d0d8", "#b9ed45"];
const pluginListing = ([slug, name, icon, summary], index) => ({
  slug,
  name,
  status: "Plugin lab candidate",
  accent: pluginAccents[index % pluginAccents.length],
  icon,
  summary,
  facts: ["Package review", "Zip package", "Installed artifact"],
});

export const wordpressPlugins = [
  ["accessibility-task-tracker", "Accessibility Task Tracker", "AT", "Track accessibility review tasks, owners, notes, and follow-up status inside WordPress."],
  ["affiliate-disclosure-manager", "Affiliate Disclosure Manager", "AD", "Manage affiliate disclosure reminders and placement checks for content review workflows."],
  ["broken-shortcode-finder", "Broken Shortcode Finder", "SC", "Find unregistered or malformed shortcode-like tokens without executing post content."],
  ["bulk-price-update-planner", "Bulk Price Update Planner", "$", "Plan bulk pricing changes with a review-first workflow before store updates are applied."],
  ["client-content-approval", "Client Content Approval", "CA", "Organize client review, approval notes, and content signoff states inside WordPress."],
  ["client-maintenance-portal", "Client Maintenance Portal", "MP", "Give maintenance clients a focused portal for status notes, requests, and service visibility."],
  ["contractor-before-after-gallery", "Contractor Before After Gallery", "BG", "Build simple before-and-after project galleries for contractor portfolio pages."],
  ["database-cleanup-planner", "Database Cleanup Planner", "DB", "Review cleanup candidates and maintenance notes before touching WordPress database data."],
  ["duplicate-media-finder", "Duplicate Media Finder", "DM", "Review exact-byte media duplicates using file size and streamed hashing without deletion automation."],
  ["form-delivery-checker", "Form Delivery Checker", "FD", "Track form delivery checks, test submissions, and follow-up notes for site maintenance."],
  ["fraud-review-checklist", "Fraud Review Checklist", "FR", "Coordinate fraud review steps, notes, and decision checkpoints for order or account triage."],
  ["image-alt-text-audit", "Image Alt Text Audit", "ALT", "Audit image alt metadata and review accessibility corrections one item at a time."],
  ["legal-page-update-reminder", "Legal Page Update Reminder", "LG", "Keep legal, policy, and compliance pages visible for scheduled review."],
  ["local-business-schema-manager", "Local Business Schema Manager", "LS", "Manage local business schema details with editable business information and review notes."],
  ["low-stock-digest", "Low Stock Digest", "LS", "Prepare low-stock summaries for WooCommerce operators and inventory review."],
  ["nap-consistency-checker", "NAP Consistency Checker", "NAP", "Check name, address, and phone consistency across local business site content."],
  ["order-export-builder", "Order Export Builder", "OE", "Create reviewed order export configurations for operational reporting workflows."],
  ["orphan-page-finder", "Orphan Page Finder", "OP", "Find pages that need internal links, review, or removal from navigation plans."],
  ["plugin-license-inventory", "Plugin License Inventory", "LI", "Track plugin licenses, renewal notes, owners, and operational status."],
  ["post-purge-pro", "Post Purge Pro", "PP", "Preview stale posts, export a CSV backup, and review batch move-to-Trash workflows."],
  ["product-compliance-expiration", "Product Compliance Expiration", "CE", "Track product compliance dates, expiration reminders, and review notes."],
  ["product-data-cleanup", "Product Data Cleanup", "PD", "Review product data quality issues before making cleanup decisions."],
  ["product-image-audit", "Product Image Audit", "PI", "Audit product image coverage, metadata, and content readiness."],
  ["redirect-manager-pro", "Redirect Manager Pro", "RM", "Plan redirect entries and review URL cleanup work inside WordPress."],
  ["returns-request-portal", "Returns Request Portal", "RR", "Organize return requests, status notes, and customer-service review steps."],
  ["scheduled-content-expiration", "Scheduled Content Expiration", "EX", "Track content expiration dates, review windows, and scheduled follow-up."],
  ["security-header-audit", "Security Header Audit", "SH", "Review website security header presence and maintenance notes."],
  ["service-area-page-builder", "Service Area Page Builder", "SA", "Create and organize service-area page drafts for local business websites."],
  ["shipping-rule-auditor", "Shipping Rule Auditor", "SR", "Review WooCommerce shipping rules, notes, and coverage gaps."],
  ["stale-content-detector", "Stale Content Detector", "SD", "Score stale content candidates with explainable freshness signals and CSV export."],
  ["stale-inventory-reporter", "Stale Inventory Reporter", "SI", "Identify old inventory records and prepare review notes for cleanup."],
  ["supplier-tracker-for-woocommerce", "Supplier Tracker for WooCommerce", "ST", "Track suppliers, product relationships, and operational notes for WooCommerce stores."],
  ["uptime-digest-plugin", "Uptime Digest Plugin", "UP", "Prepare uptime digest records and maintenance visibility for site operators."],
  ["website-maintenance-reporter", "Website Maintenance Reporter", "WR", "Summarize maintenance work, findings, and client-ready website status notes."],
  ["woocommerce-margin-calculator", "WooCommerce Margin Calculator", "MC", "Calculate and review product margin information for WooCommerce catalog planning."],
  ["wordpress-role-auditor", "WordPress Role Auditor", "RA", "Audit WordPress user roles, access notes, and permissions review status."],
].map(pluginListing);

export const roadmap = [
  ["Maxxed Remote", "Release prep", "Finish television compatibility checks, store copy, screenshots, and Play Store release preparation."],
  ["Maxxed Compass", "Release prep", "Verify navigation, trip tracking, sky guidance, notification behavior, battery use, and field accuracy."],
  ["Fishing Maxxed", "Release prep", "Complete builds, signing, known-object measurement tests, device evidence, and regulation-source review."],
  ["Maxxed Gold Estimator", "Release prep", "Run automated checks, signed builds, physical sample validation, and final privacy/store disclosures."],
  ["Maxxed Measure", "In development", "Finish camera calibration, measurement correction, history, export, and known-object validation."],
  ["Rival Rush", "Internal testing", "Continue Play internal testing, UX polish, credits, touch controls, and store listing preparation."],
];
