export const site = {
  name: "Maxxed Technical Systems",
  shortName: "Maxxed Technical",
  url: "https://techmaxxed.com",
  email: "support@techmaxxed.com",
  privacyEmail: "privacy@techmaxxed.com",
  betaEmail: "beta@techmaxxed.com",
  description: "Android-first apps and focused software for everyday control, outdoor work, measurement, field records, and friendly competition.",
};

export const apps = [
  {
    slug: "maxxed-remote",
    name: "Maxxed Remote",
    short: "Remote",
    category: "Utility",
    categoryKey: "utility",
    status: "Release verification",
    statusTone: "candidate",
    accent: "#25d0d8",
    icon: "TV",
    tagline: "Your TV. One clean remote.",
    summary: "A streamlined Android remote for compatible Samsung Tizen and LG webOS televisions, built around secure local-network control and fast everyday access.",
    description: "Control compatible televisions from one focused Android interface with discovery, pairing, saved devices, quick keypad input, app launching, and secure credential storage.",
    features: [
      ["Find compatible TVs", "Discover supported Samsung Tizen and LG webOS televisions on your local network."],
      ["Pair with confidence", "Approval and pairing credentials stay protected through Android Keystore encryption."],
      ["Keep control close", "Use navigation, volume, channels, keypad input, saved TVs, and supported app shortcuts."],
      ["Designed for local use", "Remote commands stay on the private network and only private IP addresses can be added."],
    ],
    facts: ["Android 8+", "Samsung Tizen", "LG webOS", "No ads in version 1"],
    privacy: "Pairing credentials are encrypted on the device. Remote-control traffic remains on the local network.",
    limitation: "Feature and streaming-app support varies by television model, region, and manufacturer.",
    availability: "The signed Android build is completing television compatibility checks and Play Store release preparation.",
    featureImage: "maxxed-remote-feature.png",
    screenshots: [
      ["remote-control.png", "Maxxed Remote main control screen"],
      ["remote-discovery.png", "Maxxed Remote compatible TV discovery"],
      ["remote-saved-tvs.png", "Maxxed Remote saved televisions"],
      ["remote-keypad.png", "Maxxed Remote quick keypad"],
    ],
  },
  {
    slug: "maxxed-compass",
    name: "Maxxed Compass",
    short: "Compass",
    category: "Navigation",
    categoryKey: "outdoors",
    status: "Release verification",
    statusTone: "testing",
    accent: "#b9ed45",
    icon: "N",
    tagline: "Direction, distance, and sky tools offline.",
    summary: "An offline compass, true-north guide, trip tracker, and calculated sky scanner with constellation dots and lines, local history, and practical field modes.",
    description: "Use live sensor headings, true north, trip tracking, process recovery, night display, and a calculated Sky Scanner with constellation patterns without creating an account or connecting to the internet.",
    features: [
      ["Reliable heading sources", "Uses the rotation vector with accelerometer and magnetometer fallback."],
      ["Magnetic or true north", "Applies geomagnetic declination and reports magnetic interference and calibration state."],
      ["Trips that recover", "Pause, resume, stop, segment, save locally, and recover an active trip after process loss."],
      ["Constellation Sky Scanner", "Search calculated object positions and view supported constellations as distinct star dots with connecting line patterns, a red-map mode, and optional camera preview."],
    ],
    facts: ["Offline", "True north", "Trip history", "Metric and imperial"],
    privacy: "The app requests no internet permission. Sensor, location, trip, and camera processing stays on the device.",
    limitation: "Compass accuracy depends on device sensors, calibration, magnetic conditions, and physical testing.",
    availability: "Constellation rendering is implemented. Compilation, physical heading, notification, process-recovery, outdoor distance, sky comparison, and battery verification remain in progress.",
  },
  {
    slug: "maxxed-measure",
    name: "Maxxed Measure",
    short: "Measure",
    category: "Measurement",
    categoryKey: "utility",
    status: "Active development",
    statusTone: "development",
    accent: "#ff715b",
    icon: "↔",
    tagline: "Camera-assisted measurements with honest uncertainty.",
    summary: "A reference-calibrated measuring workflow with draggable points, annotated captures, multiple units, confidence, and local history.",
    description: "Place an object of known size in the same plane as the subject, calibrate the image, adjust measurement endpoints, and save or export an annotated result with visible uncertainty.",
    features: [
      ["Calibrate with a real reference", "Use a known-size object in the same image rather than relying on an unsupported camera guess."],
      ["Correct the endpoints", "Drag both measurement points and retain a ruler overlay while reviewing the subject."],
      ["Use practical units", "View inches, common fractions, feet, millimeters, centimeters, or meters."],
      ["Keep the evidence", "Save, rename, delete, copy, and explicitly export measurements and annotated captures."],
    ],
    facts: ["CameraX", "Known reference", "Multiple units", "Local history"],
    privacy: "Measurement captures and history are designed to remain local unless the user explicitly exports them.",
    limitation: "Camera-assisted measurements are estimates. The app will not claim exact or .001-inch accuracy.",
    availability: "Core CameraX, calibration, correction, history, export, and known-object validation work is in progress.",
  },
  {
    slug: "maxxed-gold-estimator",
    name: "Maxxed Gold Estimator",
    short: "Gold Estimator",
    category: "Field analysis",
    categoryKey: "outdoors",
    status: "Release verification",
    statusTone: "testing",
    accent: "#ffc44d",
    icon: "Au",
    tagline: "Conservative visual estimates, never assay claims.",
    summary: "An offline visual material estimator with guided multi-angle capture, reference scale, mask correction, material review, saved batches, and CSV export.",
    description: "Capture six views, calibrate against a known reference, review the subject mask and visible material assignments, then produce conservative ranges and confidence notes entirely on the device.",
    features: [
      ["Guided six-angle capture", "Collect top, front, right, back, left, and low-oblique views with coverage and image-quality checks."],
      ["User-reviewed analysis", "Adjust mask sensitivity and explicitly confirm or change every visible-material cluster."],
      ["Coherent estimate ranges", "Review visible share, density, volume, weight, and confidence ranges with gold listed first."],
      ["Compare and export", "Save local batches, compare two results, copy a summary, or choose a CSV destination."],
    ],
    facts: ["Offline analysis", "Six views", "User correction", "CSV export"],
    privacy: "Captures remain in app-private storage and leave only when the user chooses an export destination.",
    limitation: "Color and surface appearance cannot identify chemistry. Results are not an assay or a valuation.",
    availability: "The requested workflow is implemented. Automated checks, signed builds, physical fixture testing, and final disclosures remain in progress.",
  },
  {
    slug: "fishing-maxxed",
    name: "Fishing Maxxed",
    short: "Fishing",
    category: "Outdoors",
    categoryKey: "outdoors",
    status: "Release verification",
    statusTone: "testing",
    accent: "#47b7ff",
    icon: "FM",
    tagline: "A private catch journal built around evidence.",
    summary: "An offline-first catch journal with guided photos, known-reference length measurement, uncertainty, manual species confirmation, and privacy-minded exports.",
    description: "Photograph a catch, measure it against a real reference, adjust the endpoints, confirm the species yourself, and keep a local record without exposing exact coordinates by default.",
    features: [
      ["Reference-based measurement", "Measure length from a known reference with draggable correction handles and visible uncertainty."],
      ["User-confirmed records", "Species identification remains an explicit user decision rather than an automated claim."],
      ["Private local journal", "Store catch records on the current device and redact exact coordinates from standard exports."],
      ["Truthful rule handling", "Regulation fixtures can exercise the evaluator but cannot authorize keeping a fish."],
    ],
    facts: ["Offline-first", "Catch history", "Location redaction", "Local rankings"],
    privacy: "Catch records stay private on the device, and default exports redact exact coordinates.",
    limitation: "Users must check current official fishing regulations. The app cannot authorize a catch as legal to keep.",
    availability: "Functional source is present. Build, signing, known-object measurement tests, device evidence, and regulation-source verification remain in progress.",
  },
  {
    slug: "rival-rush",
    name: "Rival Rush",
    short: "Rival Rush",
    category: "Party game",
    categoryKey: "games",
    status: "Internal testing",
    statusTone: "candidate",
    accent: "#ff5fb7",
    icon: "RR",
    tagline: "Fast local competition for two.",
    summary: "A colorful couples party arcade featuring PickOff, RPS Arena, Tap Battle, and Word Rush, with profiles, scores, avatars, and more games planned.",
    description: "Jump between short competitive mini-games made for couples and friends on the same device, with quick resets, readable scores, player identity, and touch-first controls.",
    features: [
      ["PickOff", "Enter choices, watch rapid eliminations, and keep a short winners history."],
      ["RPS Arena", "Play scored rock-paper-scissors rounds with ties, wins, and an optional one-round bot."],
      ["Tap Battle", "Race for taps against another player or an optional opponent mode."],
      ["Word Rush", "Use mobile A-Z controls to reveal words, track mistakes, and start a fresh round."],
    ],
    facts: ["Android first", "Local multiplayer", "Four mini-games", "Internal test"],
    privacy: "Player profiles and game progress are designed for local play; store disclosures will reflect the final advertising configuration.",
    limitation: "Features and visual polish can change during internal testing.",
    availability: "The Android build is in Google Play internal testing while UX, credits, and Word Rush receive their final pass.",
  },
];

const pluginAccents = ["#7dd3fc", "#86efac", "#facc15", "#fb7185", "#c084fc", "#25d0d8", "#b9ed45"];
const pluginListing = ([slug, name, icon, summary], index) => ({
  slug,
  name,
  status: "WordPress tool",
  accent: pluginAccents[index % pluginAccents.length],
  icon,
  summary,
  facts: ["WordPress admin", "Review workflow", "Configurable"],
});

export const wordpressPlugins = [
  ["accessibility-task-tracker", "Accessibility Task Tracker", "AT", "Track accessibility review tasks, owners, notes, and follow-up status inside WordPress."],
  ["affiliate-disclosure-manager", "Affiliate Disclosure Manager", "AD", "Manage affiliate disclosure reminders and placement checks for content review workflows."],
  ["broken-shortcode-finder", "Broken Shortcode Finder", "SC", "Find unregistered or malformed shortcode-like tokens without executing post content."],
  ["bulk-price-update-planner", "Bulk Price Update Planner", "$", "Plan bulk pricing changes with a review-first workflow before store updates are applied."],
  ["client-content-approval", "Client Content Approval", "CA", "Organize client review, approval notes, and content signoff states inside WordPress."],
  ["client-maintenance-portal", "Client Maintenance Portal", "MP", "Give maintenance clients a focused portal for status notes, requests, and service visibility."],
  ["contractor-before-after-gallery", "Contractor Before After Gallery", "BG", "Build simple before-and-after project galleries for contractor portfolio pages."],
  ["database-cleanup-planner", "Database Cleanup Planner", "DB", "Review cleanup candidates and maintenance notes before touching WordPress database data."],
  ["duplicate-media-finder", "Duplicate Media Finder", "DM", "Review exact-byte media duplicates using file size and streamed hashing without deletion automation."],
  ["form-delivery-checker", "Form Delivery Checker", "FD", "Track form delivery checks, test submissions, and follow-up notes for site maintenance."],
  ["fraud-review-checklist", "Fraud Review Checklist", "FR", "Coordinate fraud review steps, notes, and decision checkpoints for order or account triage."],
  ["image-alt-text-audit", "Image Alt Text Audit", "ALT", "Audit image alt metadata and review accessibility corrections one item at a time."],
  ["legal-page-update-reminder", "Legal Page Update Reminder", "LG", "Keep legal, policy, and compliance pages visible for scheduled review."],
  ["local-business-schema-manager", "Local Business Schema Manager", "LS", "Manage local business schema details with editable business information and review notes."],
  ["low-stock-digest", "Low Stock Digest", "LS", "Prepare low-stock summaries for WooCommerce operators and inventory review."],
  ["nap-consistency-checker", "NAP Consistency Checker", "NAP", "Check name, address, and phone consistency across local business site content."],
  ["order-export-builder", "Order Export Builder", "OE", "Create reviewed order export configurations for operational reporting workflows."],
  ["orphan-page-finder", "Orphan Page Finder", "OP", "Find pages that need internal links, review, or removal from navigation plans."],
  ["plugin-license-inventory", "Plugin License Inventory", "LI", "Track plugin licenses, renewal notes, owners, and operational status."],
  ["post-purge-pro", "Post Purge Pro", "PP", "Preview stale posts, export a CSV backup, and review batch move-to-Trash workflows."],
  ["product-compliance-expiration", "Product Compliance Expiration", "CE", "Track product compliance dates, expiration reminders, and review notes."],
  ["product-data-cleanup", "Product Data Cleanup", "PD", "Review product data quality issues before making cleanup decisions."],
  ["product-image-audit", "Product Image Audit", "PI", "Audit product image coverage, metadata, and content readiness."],
  ["redirect-manager-pro", "Redirect Manager Pro", "RM", "Plan redirect entries and review URL cleanup work inside WordPress."],
  ["returns-request-portal", "Returns Request Portal", "RR", "Organize return requests, status notes, and customer-service review steps."],
  ["scheduled-content-expiration", "Scheduled Content Expiration", "EX", "Track content expiration dates, review windows, and scheduled follow-up."],
  ["security-header-audit", "Security Header Audit", "SH", "Review website security header presence and maintenance notes."],
  ["service-area-page-builder", "Service Area Page Builder", "SA", "Create and organize service-area page drafts for local business websites."],
  ["shipping-rule-auditor", "Shipping Rule Auditor", "SR", "Review WooCommerce shipping rules, notes, and coverage gaps."],
  ["stale-content-detector", "Stale Content Detector", "SD", "Score stale content candidates with explainable freshness signals and CSV export."],
  ["stale-inventory-reporter", "Stale Inventory Reporter", "SI", "Identify old inventory records and prepare review notes for cleanup."],
  ["supplier-tracker-for-woocommerce", "Supplier Tracker for WooCommerce", "ST", "Track suppliers, product relationships, and operational notes for WooCommerce stores."],
  ["uptime-digest-plugin", "Uptime Digest Plugin", "UP", "Prepare uptime digest records and maintenance visibility for site operators."],
  ["website-maintenance-reporter", "Website Maintenance Reporter", "WR", "Summarize maintenance work, findings, and client-ready website status notes."],
  ["woocommerce-margin-calculator", "WooCommerce Margin Calculator", "MC", "Calculate and review product margin information for WooCommerce catalog planning."],
  ["wordpress-role-auditor", "WordPress Role Auditor", "RA", "Audit WordPress user roles, access notes, and permissions review status."],
].map(pluginListing);

export const roadmap = [
  ["Maxxed Remote", "Release verification", "Complete television compatibility checks and Play Store release preparation."],
  ["Maxxed Compass", "Release verification", "Compile and verify constellation guidance, navigation, tracking, and battery behavior on device."],
  ["Fishing Maxxed", "Release verification", "Complete builds, signing, known-object testing, and regulation-source verification."],
  ["Maxxed Gold Estimator", "Release verification", "Run automated fixtures, signed builds, and physical sample validation."],
  ["Maxxed Measure", "Active development", "Finalize camera calibration, measurement correction, history, export, and known-object validation."],
  ["Rival Rush", "Internal testing", "Finish Word Rush, credits, navigation, and Android internal-test polish."],
  ["WordPress Bulk Content Cleanup", "Next product", "Build controlled bulk auditing and cleanup after the current app release queue."],
];
