export const TABLES = Object.freeze([
  "users",
  "role_assignments",
  "access_role_events",
  "products",
  "builds",
  "releases",
  "qa_plans",
  "qa_executions",
  "bugs",
  "beta_applications",
  "beta_feedback",
  "beta_enrollment_events",
  "beta_track_syncs",
  "beta_data_requests",
  "automation_jobs",
  "runner_nodes",
  "test_evidence_objects",
  "test_schedules",
  "backup_snapshots",
  "support_cases",
  "incidents",
  "integration_states",
  "knowledge_base_entries",
  "knowledge_base_revisions",
  "readiness_evidence",
  "security_findings",
  "readiness_snapshots",
  "audit_events",
]);

export const TABLE_KEYS = Object.freeze({
  users: "id",
  role_assignments: "id",
  access_role_events: "id",
  products: "id",
  builds: "id",
  releases: "id",
  qa_plans: "id",
  qa_executions: "id",
  bugs: "id",
  beta_applications: "id",
  beta_feedback: "id",
  beta_enrollment_events: "id",
  beta_track_syncs: "id",
  beta_data_requests: "id",
  automation_jobs: "id",
  runner_nodes: "id",
  test_evidence_objects: "id",
  test_schedules: "id",
  backup_snapshots: "id",
  support_cases: "id",
  incidents: "id",
  integration_states: "id",
  knowledge_base_entries: "id",
  knowledge_base_revisions: "id",
  readiness_evidence: "id",
  security_findings: "id",
  readiness_snapshots: "id",
  audit_events: "id",
});
