export const TABLES = Object.freeze([
  "users",
  "role_assignments",
  "products",
  "builds",
  "releases",
  "qa_plans",
  "qa_executions",
  "bugs",
  "beta_applications",
  "beta_feedback",
  "automation_jobs",
  "runner_nodes",
  "support_cases",
  "incidents",
  "integration_states",
  "knowledge_base_entries",
  "readiness_snapshots",
  "audit_events",
]);

export const TABLE_KEYS = Object.freeze({
  users: "id",
  role_assignments: "id",
  products: "id",
  builds: "id",
  releases: "id",
  qa_plans: "id",
  qa_executions: "id",
  bugs: "id",
  beta_applications: "id",
  beta_feedback: "id",
  automation_jobs: "id",
  runner_nodes: "id",
  support_cases: "id",
  incidents: "id",
  integration_states: "id",
  knowledge_base_entries: "id",
  readiness_snapshots: "id",
  audit_events: "id",
});
