-- Repeatable commerce seed data for Maxxed admin D1.
-- Use after migrations have created commerce tables.

INSERT INTO commerce_groups (id,slug,name,buyer_type,purchase_mode,description,created_at,updated_at) VALUES
('group_business','business','Maxxed Business Tools','business','business_workspace','Business-facing request, ticket, client, quote, plugin, and admin tools with business, seat, and usage billing.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('group_plugins','plugins','Plugin Tools','individual_or_business','standalone_or_bundle','Individual plugins, small plugin bundles, and business-suite inclusions. Plugins are an acquisition channel, not a single forced suite.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('group_field','field','Field Tools','individual','standalone_first','Niche field apps stay individually purchasable first because each buyer segment is different.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('group_career','career','Career Tools','individual','standalone_or_bundle','Job search, tracking, clipper, resume, interview, and follow-up workflows.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('group_utility','utility','Everyday Utilities','individual','standalone_or_pass','Remote, compass, measure, cleanup, and practical device utilities.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT(slug) DO UPDATE SET name=excluded.name,buyer_type=excluded.buyer_type,purchase_mode=excluded.purchase_mode,description=excluded.description,updated_at=CURRENT_TIMESTAMP;

INSERT INTO commerce_products (id,slug,name,group_slug,product_type,sales_status,demo_model,demo_limit,standalone,bundle_eligible,stripe_mode,support_email,checkout_state,entitlement_key,notes,created_at,updated_at) VALUES
('commerce_post_purge_pro','post-purge-pro','Post Purge Pro','plugins','wordpress_plugin','demo_ready','usage_free','Preview 50 posts and export 1 CSV before upgrade.',1,1,'subscription','support@techmaxxed.com','not_connected','plugin.post_purge_pro','First plugin commerce test: preview, export, confirm, trash-only cleanup.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('commerce_job_tracker','job-application-tracker','Job Application Tracker','career','web_app_plus_extension','build_next','usage_free','Track 10 applications or run 10 clipper saves before upgrade.',1,1,'subscription','support@techmaxxed.com','not_connected','career.job_tracker','Best plugin/browser launch lane for fast visibility and low storage risk.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('commerce_business_requests','business-request-hub','Business Request Hub','business','business_saas','build_next','trial','14-day trial with 1 business, 1 seat, and limited requests.',1,1,'business_seat_usage','support@techmaxxed.com','not_connected','business.request_hub','First business SaaS billing test for support, contact, and request workflow.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('commerce_maxxed_measure','maxxed-measure','Maxxed Measure','field','android_app','demo_planned','free_saved_projects','3 saved measurements before Pro upgrade.',1,0,'subscription','support@techmaxxed.com','not_connected','field.maxxed_measure','Field products remain individually purchasable first.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('commerce_gold_estimator','maxxed-gold-estimator','Maxxed Gold Estimator','field','android_app','demo_planned','usage_free','3 saved estimates before Pro upgrade.',1,0,'subscription','support@techmaxxed.com','not_connected','field.gold_estimator','Higher individual pricing because the buyer is niche and value-driven.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('commerce_fishing_maxxed','fishing-maxxed','Fishing Maxxed','field','android_app','demo_planned','free_saved_records','5 catch records before Pro upgrade.',1,0,'subscription','support@techmaxxed.com','not_connected','field.fishing_maxxed','Individual first; bundle only after actual overlap is proven.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT(slug) DO UPDATE SET name=excluded.name,group_slug=excluded.group_slug,product_type=excluded.product_type,sales_status=excluded.sales_status,demo_model=excluded.demo_model,demo_limit=excluded.demo_limit,standalone=excluded.standalone,bundle_eligible=excluded.bundle_eligible,stripe_mode=excluded.stripe_mode,support_email=excluded.support_email,checkout_state=excluded.checkout_state,entitlement_key=excluded.entitlement_key,notes=excluded.notes,updated_at=CURRENT_TIMESTAMP;

INSERT INTO commerce_plans (id,slug,name,group_slug,billing_model,monthly_usd,annual_usd,trial_days,included_seats,included_actions,included_storage_gb,extra_seat_usd,overage_unit,overage_usd,overage_policy,status,created_at,updated_at) VALUES
('plan_plugin_starter','plugin-starter','Individual Plugin Pro','plugins','per_product_subscription',4.99,49.00,7,1,250,0.25,NULL,NULL,NULL,'upgrade_prompt','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('plan_plugin_bundle','plugin-bundle','Plugin Bundle','plugins','bundle_subscription',9.99,99.00,7,1,1000,1,NULL,NULL,NULL,'upgrade_prompt','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('plan_business_starter','business-starter','Business Starter','business','business_plus_seats_plus_usage',19.00,190.00,14,1,100,1,12.00,'1000 actions',10.00,'metered_after_allowance','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('plan_business_pro','business-pro','Business Pro','business','business_plus_seats_plus_usage',49.00,490.00,14,3,1000,5,10.00,'1000 actions',10.00,'metered_after_allowance','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('plan_business_scale','business-scale','Business Scale','business','business_plus_seats_plus_usage',99.00,990.00,14,10,5000,20,8.00,'1000 actions',8.00,'metered_after_allowance','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('plan_field_individual','field-individual','Field Tool Individual','field','per_product_subscription',7.99,79.00,7,1,500,1,NULL,NULL,NULL,'upgrade_prompt','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT(slug) DO UPDATE SET name=excluded.name,group_slug=excluded.group_slug,billing_model=excluded.billing_model,monthly_usd=excluded.monthly_usd,annual_usd=excluded.annual_usd,trial_days=excluded.trial_days,included_seats=excluded.included_seats,included_actions=excluded.included_actions,included_storage_gb=excluded.included_storage_gb,extra_seat_usd=excluded.extra_seat_usd,overage_unit=excluded.overage_unit,overage_usd=excluded.overage_usd,overage_policy=excluded.overage_policy,status=excluded.status,updated_at=CURRENT_TIMESTAMP;

INSERT INTO usage_meters (id,meter_key,label,unit,warning_threshold,critical_threshold,status,created_at) VALUES
('meter_actions','actions','Product actions','action',0.7,0.85,'active',CURRENT_TIMESTAMP),
('meter_storage_gb','storage_gb','Storage','GB',0.7,0.85,'active',CURRENT_TIMESTAMP),
('meter_seats','seats','Seats','seat',0.8,0.95,'active',CURRENT_TIMESTAMP),
('meter_uploads','uploads','Uploads','upload',0.7,0.85,'active',CURRENT_TIMESTAMP),
('meter_exports','exports','Exports','export',0.75,0.9,'active',CURRENT_TIMESTAMP)
ON CONFLICT(meter_key) DO UPDATE SET label=excluded.label,unit=excluded.unit,warning_threshold=excluded.warning_threshold,critical_threshold=excluded.critical_threshold,status=excluded.status;